google:
  api-key: ${apikey}
  photo-url: https://maps.googleapis.com/maps/api/place/phot
line.bot:
  channel-token: ${line-token}
  channel-secret: ${line-secret}
  handler.path: /callback
  
app:
  zhTW: zh-TW